import type { EventRecord } from '../../api/eventService'
import type { ShiftAssignment, EligibleVolunteer } from '../../types/assignment'
import type { Shift } from '../../types/shift'
import type { ShiftSwapRequest } from '../../types/shiftSwap'

export const previewEvents: EventRecord[] = [
  { id: 'preview-event', title: 'Community Arts Festival' },
]

export const previewShifts: Shift[] = [
  {
    id: 'preview-shift-registration',
    eventId: 'preview-event',
    roleRequirementId: 'preview-role-registration',
    title: 'Registration Desk',
    eventName: 'Community Arts Festival',
    roleRequirementName: 'Guest Services',
    startTime: '2026-10-10T09:00:00',
    endTime: '2026-10-10T12:00:00',
    capacity: 5,
    assignedCount: 3,
    remainingCapacity: 2,
    status: 'Scheduled',
    createdAt: '2026-09-01T00:00:00',
    updatedAt: '2026-09-01T00:00:00',
  },
  {
    id: 'preview-shift-stage',
    eventId: 'preview-event',
    roleRequirementId: 'preview-role-stage',
    title: 'Main Stage Support',
    eventName: 'Community Arts Festival',
    roleRequirementName: 'Event Operations',
    startTime: '2026-10-10T10:00:00',
    endTime: '2026-10-10T14:00:00',
    capacity: 8,
    assignedCount: 5,
    remainingCapacity: 3,
    status: 'Scheduled',
    createdAt: '2026-09-01T00:00:00',
    updatedAt: '2026-09-01T00:00:00',
  },
  {
    id: 'preview-shift-guest',
    eventId: 'preview-event',
    roleRequirementId: 'preview-role-guest',
    title: 'Guest Support',
    eventName: 'Community Arts Festival',
    roleRequirementName: 'Guest Services',
    startTime: '2026-10-10T13:00:00',
    endTime: '2026-10-10T17:00:00',
    capacity: 4,
    assignedCount: 2,
    remainingCapacity: 2,
    status: 'Scheduled',
    createdAt: '2026-09-01T00:00:00',
    updatedAt: '2026-09-01T00:00:00',
  },
]

export const previewAssignments: ShiftAssignment[] = [
  {
    id: 'preview-assignment-1',
    shiftId: 'preview-shift-registration',
    shiftTitle: 'Registration Desk',
    eventId: 'preview-event',
    eventName: 'Community Arts Festival',
    volunteerId: 'preview-volunteer-1',
    volunteerName: 'Alex Morgan',
    volunteerEmail: 'alex@example.test',
    status: 'Confirmed',
    assignedAt: '2026-09-20T09:00:00',
    createdAt: '2026-09-20T09:00:00',
    updatedAt: '2026-09-20T09:00:00',
  },
  {
    id: 'preview-assignment-2',
    shiftId: 'preview-shift-registration',
    shiftTitle: 'Registration Desk',
    eventId: 'preview-event',
    eventName: 'Community Arts Festival',
    volunteerId: 'preview-volunteer-2',
    volunteerName: 'Jamie Lee',
    volunteerEmail: 'jamie@example.test',
    status: 'Confirmed',
    assignedAt: '2026-09-21T09:00:00',
    createdAt: '2026-09-21T09:00:00',
    updatedAt: '2026-09-21T09:00:00',
  },
  {
    id: 'preview-assignment-3',
    shiftId: 'preview-shift-registration',
    shiftTitle: 'Registration Desk',
    eventId: 'preview-event',
    eventName: 'Community Arts Festival',
    volunteerId: 'preview-volunteer-5',
    volunteerName: 'Sam Rivera',
    volunteerEmail: 'sam@example.test',
    status: 'Confirmed',
    assignedAt: '2026-09-22T09:00:00',
    createdAt: '2026-09-22T09:00:00',
    updatedAt: '2026-09-22T09:00:00',
  },
]

export const previewEligibleVolunteers: EligibleVolunteer[] = [
  { id: 'preview-volunteer-3', fullName: 'Taylor Kim', email: 'taylor@example.test' },
  { id: 'preview-volunteer-4', fullName: 'Riley Patel', email: 'riley@example.test' },
]

export const previewSwaps: ShiftSwapRequest[] = [
  {
    id: 'preview-swap-1',
    requesterAssignmentId: 'preview-assignment-1',
    requesterVolunteerId: 'preview-volunteer-1',
    requesterName: 'Alex Morgan',
    requesterEmail: 'alex@example.test',
    sourceShiftId: 'preview-shift-registration',
    sourceShiftTitle: 'Registration Desk',
    sourceEventId: 'preview-event',
    sourceEventTitle: 'Community Arts Festival',
    targetVolunteerId: 'preview-volunteer-3',
    targetVolunteerName: 'Taylor Kim',
    targetVolunteerEmail: 'taylor@example.test',
    targetShiftId: 'preview-shift-stage',
    targetShiftTitle: 'Main Stage Support',
    targetEventId: 'preview-event',
    targetEventTitle: 'Community Arts Festival',
    reason: 'Schedule conflict',
    status: 'Pending_Organizer',
    createdAt: '2026-09-25T10:00:00',
    updatedAt: '2026-09-25T10:00:00',
  },
  {
    id: 'preview-swap-2',
    requesterAssignmentId: 'preview-assignment-2',
    requesterVolunteerId: 'preview-volunteer-2',
    requesterName: 'Jamie Lee',
    requesterEmail: 'jamie@example.test',
    sourceShiftId: 'preview-shift-registration',
    sourceShiftTitle: 'Registration Desk',
    sourceEventId: 'preview-event',
    sourceEventTitle: 'Community Arts Festival',
    targetVolunteerId: 'preview-volunteer-4',
    targetVolunteerName: 'Riley Patel',
    targetVolunteerEmail: 'riley@example.test',
    targetShiftId: 'preview-shift-guest',
    targetShiftTitle: 'Guest Support',
    targetEventId: 'preview-event',
    targetEventTitle: 'Community Arts Festival',
    reason: 'Would like to help with guest support',
    status: 'Approved',
    createdAt: '2026-09-24T10:00:00',
    updatedAt: '2026-09-26T10:00:00',
  },
  {
    id: 'preview-swap-3',
    requesterAssignmentId: 'preview-assignment-1',
    requesterVolunteerId: 'preview-volunteer-1',
    requesterName: 'Alex Morgan',
    requesterEmail: 'alex@example.test',
    sourceShiftId: 'preview-shift-stage',
    sourceShiftTitle: 'Main Stage Support',
    sourceEventId: 'preview-event',
    sourceEventTitle: 'Community Arts Festival',
    targetVolunteerId: 'preview-volunteer-2',
    targetVolunteerName: 'Jamie Lee',
    targetVolunteerEmail: 'jamie@example.test',
    targetShiftId: 'preview-shift-registration',
    targetShiftTitle: 'Registration Desk',
    targetEventId: 'preview-event',
    targetEventTitle: 'Community Arts Festival',
    reason: 'Example rejected request',
    status: 'Rejected',
    createdAt: '2026-09-22T10:00:00',
    updatedAt: '2026-09-23T10:00:00',
  },
]
